-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 09:27:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UID` VARCHAR(300) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `UID_UNIQUE` (`UID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `UID` VARCHAR(300) NOT NULL,
  `identifier` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `stationCode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`UID`, `identifier`),
  CONSTRAINT `fk_Location_Users`
    FOREIGN KEY (`UID`)
    REFERENCES `mydb`.`Users` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Journey` (
  `UID` VARCHAR(300) NOT NULL,
  `identifier` VARCHAR(45) NOT NULL,
  `originCode` VARCHAR(45) NULL DEFAULT NULL,
  `destinationCode` VARCHAR(45) NULL DEFAULT NULL,
  `departuretime` VARCHAR(45) NULL DEFAULT NULL,
  `departuredate` VARCHAR(45) NULL DEFAULT NULL,
  `orderprice` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`UID`, `identifier`),
  INDEX `fk_Journey_Users1_idx` (`UID` ASC),
  CONSTRAINT `fk_Journey_Users1`
    FOREIGN KEY (`UID`)
    REFERENCES `mydb`.`Users` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Composition` (
  `UID` VARCHAR(300) NOT NULL,
  `numberOfPassengers` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `Users_UID_UNIQUE` (`UID` ASC),
  INDEX `fk_Composition_Users1_idx` (`UID` ASC),
  CONSTRAINT `fk_Composition_Users1`
    FOREIGN KEY (`UID`)
    REFERENCES `mydb`.`Users` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
